package com.maruf.bdtaxcalculator.ui.theme

import androidx.compose.ui.graphics.Color

val TaxPrimary = Color(0xFF2E7D32)
val TaxPrimaryDark = Color(0xFF1B5E20)
val TaxSecondary = Color(0xFF00897B)
val TaxTertiary = Color(0xFF4CAF50)
val TaxBackground = Color(0xFFF1F8E9)
val TaxSurface = Color(0xFFFFFFFF)

val HomeActionBlue = Color(0xFF102B7A)
val HomeActionBlueDark = Color(0xFF0B1E57)
val HomeTextPrimary = Color(0xFF1E293B)
val HomeTextMuted = Color(0xFF64748B)
val HomeBorder = Color(0xFFE5E7EB)
val HomeSoftBlue = Color(0xFFF2F4F8)
val HomeSoftGreen = Color(0xFFF1F8F4)
val HomeSoftPurple = Color(0xFFF5F5FD)
val HomeSoftNav = Color(0xFFEFF3FF)
val HomeNavInactive = Color(0xFF94A3B8)

val CalculatorBackground = Color(0xFFF3F7F2)
val CalculatorGradientTop = Color(0xFFF5FAF5)
val CalculatorGradientMiddle = Color(0xFFEDF5EF)
val CalculatorGradientBottom = Color(0xFFF9FBF8)
val CalculatorHeroStart = Color(0xFF103A22)
val CalculatorHeroMiddle = Color(0xFF1F6F3B)
val CalculatorInk = Color(0xFF102016)
val CalculatorControlText = Color(0xFF244033)
val CalculatorFieldText = Color(0xFF4A554F)
val CalculatorMuted = Color(0xFF6B756E)
val CalculatorMutedSoft = Color(0xFF79867F)
val CalculatorSurfaceAlt = Color(0xFFF8FAF8)
val CalculatorPanel = Color(0xFFFBFDFA)
val CalculatorBorder = Color(0xFFE4E9E5)
val CalculatorDivider = Color(0xFFF1F3F1)
val CalculatorAccentSoft = Color(0xFFF2F7F3)
val CalculatorHeroPill = Color(0xFFD4E7D8)
val CalculatorSuccess = Color(0xFF1F7A39)
val CalculatorPositive = Color(0xFF81C784)
val CalculatorDanger = Color(0xFFD32F2F)
val CalculatorDangerSoft = Color(0xFFE57373)
val CalculatorDangerSoft2 = Color(0x33EC7B7B)
val CalculatorInfoBackground = Color(0xFFE3F2FD)
val CalculatorInfo = Color(0xFF1565C0)
val CalculatorInfoDark = Color(0xFF0D47A1)
val AuditDanger = Color(0xFFCF1322)
val AuditScreenBackground = Color(0xFFF4FBF6)
val AuditInputBackground = Color(0xFFFAFDFC)
val AuditDisabledButton = Color(0xFFE2E8F0)
val AuditDisabledText = Color(0xFF8FA1B5)
val AuditReadyPill = Color(0xFFE7F8ED)
val AuditReadyText = Color(0xFF2E8A57)
val AuditSelectedPill = Color(0xFFFFEFEF)
val AuditSelectedText = Color(0xFFD94A4A)
val AuditZonePill = Color(0xFFEFF4FF)
val AuditZoneText = Color(0xFF3F6FE5)
